name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node Modules
        uses: actions/cache@v4.1.2
        with:
          # The path to the directory you want to cache
          path: node_modules

          # A unique key to identify the cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

          # Optional fallback keys to use when an exact match isn't found
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

          # Optional: Chunk size for large files in bytes (default is typically fine)
          upload-chunk-size: 50000000  # 50MB

          # Optional: Enable cross-platform cache sharing (false by default)
          enableCrossOsArchive: true

          # Optional: Fail the workflow if cache is not found (false by default)
          fail-on-cache-miss: false

          # Optional: Lookup cache only without downloading it (false by default)
          lookup-only: false

          # Optional: Always save the cache, even if previous steps failed (false by default)
          save-always: false

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
